name: betatestVS
favicon: null
layout_spectrum: 0.990938686998561
typography_spectrum: 0.7373329303227365
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.15125748864375055
  lightness: 0.15231397934257984
  saturation: 0.249192766379565
  rhythmicContrast: 0.9607559517025948
purpose: []
